version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: mysql
    ports:
    - 8080:80